# Giới thiệu cơ  bản về các metric đánh giá

Giới thiệu evaluation metric là gì? Tại sao cần evaluation metric

Làm sao để biết một thuật toán, một ô hình là tốt -> cần có một cái gì đó để thể hiện nó tốt -> evaluation_metric ra đời

Bây giờ có hai thuật toán, làm thế nào để so sánh hai thuật toán với nhau -> Evaluation metric giải quyết đuuợc điều này

Phân loại các evaluation metric
- Classification metric
- Regression metric
- Ranking metric
- NLP metric
- CV metric

Chúng ta đã có công thức toán để đánh giá, Vậy phương pháp đánh giá sẽ như thế nào
Nhắc lại về bài toán dự đoánm,  dù là classification hay regression, hay ranking chúng ta có thể chia phần dự đoán làm 2 kiệu
- Dữ liệu được đào tạo là dữ liệu lịch sử, dữ liệu dữ đoán là dữ liệu  tương lai. Ví dụ bài toán phổ biến nhất là dự đoán khách hàng có rời bỏ dịch vụ hay không? Từ những dữ liệu quá khứ rời bỏ hoặc ở lại của khách hàng, chúng ta sẽ dự đoán trong tương lai khách hàng có rời bỏ dịch vụ hay không? Hay bài toán dự đoán tháng tiếp  theo, khả năng khách hàng mua món đồ của cửa hàng đó là bao nhiêu
- Dữ liệu được đào tạo là một phần dữ liệu, dữ liệu dự đoán là phần còn lại. Ví dụ bạn cần nhận biết trong số ảnh xe được upload bởi người dùng, ảnh nào là chụp phía trước xe để làm ảnh nội bật trong bài viết. Hệ thống đang có 1 triệu ảnh chưa được nhận diện, để làm một hệ thống tự động, bạn xây dựng một bộ dữ liệu huấn luyện từ một phần của 1 triệu ảnh đó ( ví dụ 10,000 ảnh) và cho máy học sau đó máy sẽ tự động nhận diện phần dữ liệu còn lại, và tất nhiên những hình ảnh trong tương lai được thêm vào máy cũng có thể nhận diện được.